### ISSUE TITLE
object not found?

### ISSUE THREAD

**Issue by domshi** [Echo343/HorsePocket#5]
the following is the log when trying to load the game

-- MOD horsepocket --
Details:
	Mod File: /C:/Users/domin/AppData/Roaming/.minecraft/mods/HorsePocket-1.19.2-0.12.0.jar
	Failure message: Horse Pocket (horsepocket) encountered an error during the sided_setup event phase
		java.lang.NullPointerException: Registry Object not present: horsepocket:pocket
	Mod Version: 0.12.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NullPointerException: Registry Object not present: horsepocket:pocket
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.2-43.1.32-universal.jar%23265!/:?] {re:mixin,re:classloading}
	at com.blargsworkshop.horsepocket.event.ClientIconHandler.doClientStuff(ClientIconHandler.java:21) ~[HorsePocket-1.19.2-0.12.0.jar%23192!/:0.12.0] {re:classloading}
	at com.blargsworkshop.horsepocket.event.__ClientIconHandler_doClientStuff_FMLClientSetupEvent.invoke(.dynamic) ~[HorsePocket-1.19.2-0.12.0.jar%23192!/:0.12.0] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.2-43.1.32.jar%23262!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.1.32.jar%23261!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by domshi** [comment]
for future reference it was the eggstra mod that caused your mod to act janky, sorry for the confusion
